version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/code/app
    environment:
      - AZURE_OPENAI_ENDPOINT=${AZURE_OPENAI_ENDPOINT}
      - AZURE_OPENAI_KEY=${AZURE_OPENAI_KEY}
      - AZURE_OPENAI_DEPLOYMENT_NAME=${AZURE_OPENAI_DEPLOYMENT_NAME}
      - AZURE_OPENAI_API_VERSION=${AZURE_OPENAI_API_VERSION}
      - AZURE_LANGUAGE_ENDPOINT=${AZURE_LANGUAGE_ENDPOINT}
      - AZURE_LANGUAGE_KEY=${AZURE_LANGUAGE_KEY}
      - AZURE_DOCUMENT_ENDPOINT=${AZURE_DOCUMENT_ENDPOINT}
      - AZURE_DOCUMENT_KEY=${AZURE_DOCUMENT_KEY}
      - AZURE_VISION_ENDPOINT=${AZURE_VISION_ENDPOINT}
      - AZURE_VISION_KEY=${AZURE_VISION_KEY}
    env_file:
      - .env
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_GITHUB_TOKEN=${REACT_APP_GITHUB_TOKEN}
      - REACT_APP_MOODLE_TOKEN=${REACT_APP_MOODLE_TOKEN}
      - REACT_APP_MOODLE_URL=${REACT_APP_MOODLE_URL}
      - REACT_APP_API_URL=http://localhost:8000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge